### ISSUE TITLE
Sierra fix

### ISSUE THREAD

**Issue by own2pwn** [slavaim/MacOSX-VFS-redirector#1]
Hello, thanks for this project! How can hardcode offset for Sierra? When I load non modified compiled kext, I have crash at v_op check in VNodeHook at line 279.
If I change it in  vnode_Yosemite struct, then I got this error ``` Cannot initialize a member subobject of type 'int (**)(void *)' with an rvalue of type 'int' ``` while this change for project `` MacOSX-FileSystem-Filter `` works fine

**Comment by slavaim** [comment]
MacOSX-FileSystem-Filter doesn't use hardcoded vnode_Yosemite structure so the change you made was skipped by a preprocessor, see #ifndef USE_FAKE_FSD preprocessor directive at the top of  VersionDependent.h .  Instead a structure inference is used. You can modify MacOSX-VFS-redirector the same way as MacOSX-FileSystem-Filter was modified to make it OS kernel version independent. Look at https://github.com/slavaim/MacOSX-FileSystem-Filter/commit/ead06c5786d47326911c844159b4cb929e9911f0 commit that activated structure inference for the MacOSX-FileSystem-Filter project or wait a little until I do this myself for this project.

**Comment by slavaim** [comment]
I added a support for Sierra(10.12) . To compile for Sierra you need either compile with 10.12 SDK to have MAC_OS_X_VERSION_MIN_REQUIRED set to MAC_OS_X_VERSION_10_12 or redefine a preprocessor condition in VersionDependent.cpp  #if !defined(MAC_OS_X_VERSION_10_11) || MAC_OS_X_VERSION_MIN_REQUIRED <= MAC_OS_X_VERSION_10_11  . 

In general you do not need Sierra SDK to compile for Sierra if you change the above preprocessor condition. 

For details look at commit diff https://github.com/slavaim/MacOSX-VFS-redirector/commit/48b7868d64b76b5da72bfce890180a0da323f028

I didn't check that the kext would load on Sierra but I checked with lldb that the offsets for the vnode structure were correct.

VFSFilter0`QvrGetVnodeOpVector(vnode*) at VersionDependent.cpp:360:
VFSFilter0[0x36d0]:  pushq  %rbp
VFSFilter0[0x36d1]:  movq   %rsp, %rbp
VFSFilter0[0x36d4]:  pushq  %rax
VFSFilter0[0x36d5]:  movq   %rdi, -0x8(%rbp)
VFSFilter0[0x36d9]:  movq   -0x8(%rbp), %rdi
VFSFilter0[0x36dd]:  movq   0xd0(%rdi), %rax
VFSFilter0[0x36e4]:  addq   $0x8, %rsp
VFSFilter0[0x36e8]:  popq   %rbp
VFSFilter0[0x36e9]:  ret  

0xd0 is a correct offset for the v_op field in Sierra.

**Comment by own2pwn** [comment]
Hey there, first of all, thanks for fast reply and fix! But now there is another crash.
Log fragment: 
`*** Panic Report ***
panic(cpu 3 caller 0xffffff800fef357e): /.../VFSFilter0/VFSHooks.cpp:541 Assertion failed: inData.Parameters.Filter.out.replyWasReceived || inData.Parameters.Filter.out.noClient
Backtrace (CPU 3), Frame : Return Address
0xffffff90dfaf3830 : 0xffffff800fef368c 
0xffffff90dfaf38b0 : 0xffffff800fef357e 
0xffffff90dfaf38d0 : 0xffffff7f9206a602 
0xffffff90dfaf3ac0 : 0xffffff8010116bae 
0xffffff90dfaf3b90 : 0xffffff8010115db1 
0xffffff90dfaf3cb0 : 0xffffff801012d440 
0xffffff90dfaf3d00 : 0xffffff80100ff347 
0xffffff90dfaf3f00 : 0xffffff80100ff257 
0xffffff90dfaf3f50 : 0xffffff8010427cba 
0xffffff90dfaf3fb0 : 0xffffff800fea5f46 
      Kernel Extensions in backtrace:
         com.VFSFilter0(1.0)[EA998292-C8B0-37B0-87D5-C09DBCD6C191]@0xffffff7f92066000->0xffffff7f9208afff` 

I made some tests and it seems that I got this exception when I save file manually or system does auto saving (rarer case)
if we can speak Russian, I can describe the problem more detailed (if it is needed)

maybe can you recommend me some books to read about drivers developing for beginners?

**Comment by slavaim** [comment]
This is a panic triggered by an assertion. You are running a debug build. Use a release build to compile without assertions. The failed assertion probably points to some problems in communication with a user client. If you want to continue with a debug build you can either modify the failed assertion or resolve conditions that resulted in assertion failure.

**Comment by own2pwn** [comment]
sorr for stupid issues

**Comment by slavaim** [comment]
Some comments on books - 
My favorite book on Mac OS X internals is Amit Singh's "Mac OS X Internals: A Systems Approach" , the book is 10 years old but still is the best. Skip PowerPC related discussion. Next is J Levin's "Mac OS X and iOS Internals: To the Apple's Core". There is also a pretty basic book on drivers development Halvorsen and Clarke's "OS X and iOS Kernel Programming", you should start from this one if you are not going to dig deep in the OS kernel and just need a jump start into drivers development.
