### ISSUE TITLE
not work in macos 10.12.1

### ISSUE THREAD

**Issue by sdhzdmzzl** [slavaim/MacOSX-VFS-redirector#2]
hi,I downloaded this code to my mac.my mac is 10.12.1.
I have created /work1/my_word folder.
My Word version is 2016.
after I compiled the codes. I copy kext file to /tmp and use kextutil command to load the kext.
then ,I start vfsfiterclient.

after these steps, I start Word.  and the mac is crashed and then reboot.
after reboot, the crash message shows:
Anonymous UUID:       79D022C7-CA5A-9DB2-8878-90031B078CB0

Wed Nov 29 15:20:11 2017

*** Panic Report ***
panic(cpu 1 caller 0xffffff80076f357e): /Users/aaaaa/Desktop/MacOSX-VFS-redirector-master/VFSFilter0/VFSFilter0/VFSHooks.cpp:541 Assertion failed: inData.Parameters.Filter.out.replyWasReceived || inData.Parameters.Filter.out.noClient
Backtrace (CPU 1), Frame : Return Address
0xffffff8871653730 : 0xffffff80076f368c 
0xffffff88716537b0 : 0xffffff80076f357e 
0xffffff88716537d0 : 0xffffff7f8adae7c9 
0xffffff88716539c0 : 0xffffff8007916bae 
0xffffff8871653a90 : 0xffffff8007915db1 
0xffffff8871653bb0 : 0xffffff800792d440 
0xffffff8871653c00 : 0xffffff8007932a17 
0xffffff8871653f20 : 0xffffff80079332ca 
0xffffff8871653f50 : 0xffffff8007c27cba 
0xffffff8871653fb0 : 0xffffff80076a5f46 
      Kernel Extensions in backtrace:
         com.VFSFilter0(1.0)[6385E4F9-DF0D-378B-979F-BE3B8F8EB265]@0xffffff7f8adaa000->0xffffff7f8adcefff

BSD process name corresponding to current thread: Microsoft Word

Mac OS version:
16B2657

Kernel version:
Darwin Kernel Version 16.1.0: Wed Oct 19 20:31:56 PDT 2016; root:xnu-3789.21.4~4/RELEASE_X86_64
Kernel UUID: 75CA1C4D-7BF4-321B-B544-D8F1B6D60EF8
Kernel slide:     0x0000000007400000
Kernel text base: 0xffffff8007600000
__HIB  text base: 0xffffff8007500000
System model name: VMware7,1 (MAHOBAY)

System uptime in nanoseconds: 934591497719
last loaded kext at 878717939990: com.VFSFilter0	1 (addr 0xffffff7f8adaa000, size 151552)
last unloaded kext at 99605894927: com.apple.driver.AppleXsanScheme	3 (addr 0xffffff7f8a4bb000, size 40960)
loaded kexts:
com.VFSFilter0	1
com.vmware.kext.vmhgfs	0430.16.79
com.vmware.kext.vmmemctl	0430.16.79
com.vmware.kext.VMwareGfx	0430.16.79
net.lundman.zfs	1.6.1
net.lundman.spl	1.6.1
com.apple.filesystems.smbfs	3.1
com.apple.driver.AudioAUUC	1.70
com.apple.filesystems.autofs	3.0
com.apple.driver.AppleOSXWatchdog	1
com.apple.driver.AppleHDA	278.23
com.apple.driver.AppleUpstreamUserClient	3.6.4
com.apple.driver.pmtelemetry	1
com.apple.iokit.IOUserEthernet	1.0.1
com.apple.driver.ACPI_SMC_PlatformPlugin	1.0.0
com.apple.driver.AppleMCCSControl	1.2.13
com.apple.iokit.IOBluetoothSerialManager	5.0.1f7
com.apple.Dont_Steal_Mac_OS_X	7.0.0
com.apple.driver.AppleHV	1
com.apple.driver.AppleIntelSlowAdaptiveClocking	4.0.0
com.apple.iokit.SCSITaskUserClient	394
com.apple.AppleFSCompression.AppleFSCompressionTypeDataless	1.0.0d1
com.apple.AppleFSCompression.AppleFSCompressionTypeZlib	1.0.0
com.apple.BootCache	40
com.apple.filesystems.hfs.kext	366.1.1
com.apple.iokit.IOAHCIBlockStorage	295.20.1
com.apple.driver.AppleAHCIPort	326
com.apple.driver.AppleLSIFusionMPT	3.8.0
com.apple.driver.Intel82574LEthernet	2.7.2
com.apple.driver.AppleIntelPIIXATA	2.5.1
com.apple.driver.AppleACPIButtons	5.0
com.apple.driver.AppleHPET	1.8
com.apple.driver.AppleRTC	2.0
com.apple.driver.AppleSMBIOS	2.1
com.apple.driver.AppleAPIC	1.7
com.apple.nke.applicationfirewall	172
com.apple.security.quarantine	3
com.apple.security.TMSafetyNet	8
com.apple.kext.triggers	1.0
com.apple.driver.DspFuncLib	278.23
com.apple.kext.OSvKernDSPLib	525
com.apple.iokit.IOSurface	153.1
com.apple.driver.AppleHDAController	278.23
com.apple.iokit.IOHDAFamily	278.23
com.apple.iokit.IOAudioFamily	205.11
com.apple.vecLib.kext	1.2.0
com.apple.driver.IOPlatformPluginLegacy	1.0.0
com.apple.driver.IOPlatformPluginFamily	6.0.0d8
com.apple.driver.AppleSMBusController	1.0.14d1
com.apple.iokit.IOSMBusFamily	1.1
com.apple.iokit.IOSerialFamily	11
com.apple.iokit.IOBluetoothFamily	5.0.1f7
com.apple.driver.AppleSMC	3.1.9
com.apple.driver.AppleSSE	1.0
com.apple.iokit.IOSlowAdaptiveClockingFamily	1.0.0
com.apple.iokit.IONDRVSupport	2.4.1
com.apple.iokit.IOGraphicsFamily	2.4.1
com.apple.driver.usb.IOUSBHostHIDDevice	1.1
com.apple.driver.AppleUSBHostMergeProperties	1.1
com.apple.driver.usb.networking	5.0.0
com.apple.driver.usb.AppleUSBHostCompositeDevice	1.1
com.apple.driver.usb.AppleUSBHub	1.1
com.apple.iokit.IOSCSIMultimediaCommandsDevice	394
com.apple.iokit.IOBDStorageFamily	1.8
com.apple.iokit.IODVDStorageFamily	1.8
com.apple.iokit.IOCDStorageFamily	1.8
com.apple.filesystems.hfs.encodings.kext	1
com.apple.driver.usb.AppleUSBHostPacketFilter	1.0
com.apple.iokit.IOUSBFamily	900.4.1
com.apple.iokit.IOAHCISerialATAPI	266
com.apple.driver.usb.AppleUSBEHCIPCI	1.1
com.apple.driver.usb.AppleUSBXHCIPCI	1.1
com.apple.driver.usb.AppleUSBXHCI	1.1
com.apple.driver.usb.AppleUSBUHCIPCI	1.1
com.apple.driver.usb.AppleUSBUHCI	1.1
com.apple.driver.usb.AppleUSBEHCI	1.1
com.apple.iokit.IOAHCIFamily	288
com.apple.iokit.IOSCSIParallelFamily	3.0.0
com.apple.iokit.IOSCSIArchitectureModelFamily	394
com.apple.iokit.IONetworkingFamily	3.2
com.apple.iokit.IOATAFamily	2.5.3
com.apple.driver.AppleEFINVRAM	2.1
com.apple.driver.AppleEFIRuntime	2.0
com.apple.iokit.IOHIDFamily	2.0.0
com.apple.security.sandbox	300.0
com.apple.kext.AppleMatch	1.0.0d1
com.apple.driver.AppleKeyStore	2
com.apple.driver.AppleMobileFileIntegrity	1.0.5
com.apple.driver.AppleCredentialManager	1.0
com.apple.driver.KernelRelayHost	1
com.apple.iokit.IOUSBHostFamily	1.1
com.apple.driver.AppleBusPowerController	1.0
com.apple.driver.DiskImages	444.20.3
com.apple.iokit.IOStorageFamily	2.1
com.apple.iokit.IOReportFamily	31
com.apple.driver.AppleFDEKeyStore	28.30
com.apple.driver.AppleACPIPlatform	5.0
com.apple.iokit.IOPCIFamily	2.9
com.apple.iokit.IOACPIFamily	1.4
com.apple.kec.Libm	1
com.apple.kec.pthread	1
com.apple.kec.corecrypto	1.0
Model: VMware7,1, BootROM VMW71.00V.0.B64.1507021939, 2 processors, 3.23 GHz, 2 GB, SMC 1.16f8
Graphics: Display, PCI, 128 MB
Memory Module: RAM slot #0/RAM slot #0, 2 GB, DRAM, 0 MHz, VMware Virtual RAM, VMW-2048MB
Network Service: Ethernet, Ethernet, en0
Serial ATA Device: VMware Virtual SATA Hard Drive, 85.9 GB
Serial ATA Device: VMware Virtual SATA CDRW Drive
USB Device: USB 3.0 Bus
USB Device: VMware Virtual USB Hub
USB Device: VMware Virtual USB Hub
USB Device: VMware Virtual USB Hub
USB Device: VMware Virtual USB Hub
USB Device: VMware Virtual USB Keyboard
USB Device: VMware Virtual USB Mouse
USB Device: USB 2.0 Bus
USB Device: USB Bus
USB Device: VMware Virtual USB Hub
Thunderbolt Bus: 

thanks for your future reply.

update:
I comment "assert(inData.Parameters.Filter.out.replyWasReceived || inData.Parameters.Filter.out.noClient)".
It works.but after I writed something in Word and saved.Word can't saved.

**Comment by slavaim** [comment]
Hi,

The first panic was because you built a debug build with asserts and loaded the module without a user mode client or something wrong with the client. 
Regarding the second issue I am unable to assist as there are too many conditions that affect the filter operation and I can't single out the one for this particular case from the description.

**Comment by sdhzdmzzl** [comment]
thanks for your reply.
I found that Word can't save is because sandbox denied.but I don't know why. without the kext, Word can save.
I'll try vi and will be back soon to update.

**Comment by slavaim** [comment]
You need to extend gApplicationsData for vi executable.

**Comment by sdhzdmzzl** [comment]
I'm back to update:
1:I add vi item to gApplicationsData  but It doesn't work. I use vi to edit or create a file , the client doesn't receive anything. 
the code is:
const static ApplicationData   gApplicationsData[2][4] =
{
    //
    // CreateNew
    //
    {
        {
            .applicationShortName = "Microsoft Word",
            .redirectTo = WordDirectory,
            .redirectIO = true
        },
        
        {
            .applicationShortName = "vi",
            .redirectTo = WordDirectory,
            .redirectIO = true
        },
        
        
        {
            .applicationShortName = "Preview",
            .redirectTo = "/work1/my_preview",
            .redirectIO = true
        },
        
        {
            .applicationShortName = "AdobeReader",
            .redirectTo = "/work1/my_adobe",
            .redirectIO = true
        },
    },
    
    //
    // OpenExisting
    //
    {
        {
            .applicationShortName = "Microsoft Word",
            .redirectTo = WordDirectory,
            .redirectIO = false
        },
        {
            .applicationShortName = "vi",
            .redirectTo = WordDirectory,
            .redirectIO = false
        },
        
        {
            .applicationShortName = "Preview",
            .redirectTo = "/work1/my_preview",
            .redirectIO = false
        },
        
        {
            .applicationShortName = "AdobeReader",
            .redirectTo = "/work1/my_adobe",
            .redirectIO = false
        },
    }
};
2:I installed office 2011.It works. But I also don't know why Office 2016 not work.maybe sandbox?But without the kext, Office 2016 works.

**Comment by slavaim** [comment]
".redirectTo = WordDirectory," - I am not sure this path is correct as it might be a relative path(I don't remember details) to the current task directory. Try the absolute path like "/work1/vi" and don't forget to create this directory before testing.

**Comment by sdhzdmzzl** [comment]
thanks I'll try.

**Comment by slavaim** [comment]
Actually, this particular version requires tailoring for some applications as it doesn't process all possible cases.

**Comment by sdhzdmzzl** [comment]
It doesn't work.I'll try to find the reasons.
Do you test office 2016? In my Mac. office 2011 works, But Office 2016 doesn't work.
anyway, thanks for your help.

**Comment by slavaim** [comment]
Use DTrace ( e.g. dtruss command ) to trace application syscalls. This provide you with some information about what was wrong.

**Comment by slavaim** [comment]
I've just discovered that there is a debug code in the project

        if( ! CmdIsExtensionEqual( ap->a_cnp->cn_nameptr, ".docx" ) &&
           ! CmdIsExtensionEqual( ap->a_cnp->cn_nameptr, ".tmp" ) ){
            
            //
            // for the TEST we are only interested in docx files
            //
            goto __exit;
        }

This might be the reason of the problem at least in case of vi.
