### ISSUE TITLE
shadow file and redirect file

### ISSUE THREAD

**Issue by sdhzdmzzl** [slavaim/MacOSX-VFS-redirector#3]
I've read and test this project for days.sorry for my poor knowledge about osx dirve developing.I'm not able to understand why there are shadow files and redirect files?
If there are only redirect files, and move shadow files to original files, what will happen?
thanks for your replys.

**Comment by slavaim** [comment]
I believe if you don't have any specific requirements for data flow processing ( as was a case when this redirector was developed ) you can get rid of a shadow or redirected file ( depending on your requirements ).

**Comment by sdhzdmzzl** [comment]
thanks for your replys.
