### ISSUE TITLE
where did the kext copy data to shadow file

### ISSUE THREAD

**Issue by sdhzdmzzl** [slavaim/MacOSX-VFS-redirector#4]
I found codes in QvrVnopLookupHookEx2, after vnode_open shadowPath, the codes copy data to shadow file were commented. But in fact, the data were copied to shadow files.I'm confused which code copy data?
the usermode client did copy file data to redirect file.

**Comment by sdhzdmzzl** [comment]
does QvrReadInCacheFromBackingFile copy?

**Comment by slavaim** [comment]
It is copied by a user mode client. 

QvrReadInCacheFromBackingFile just fills the cache memory pages with file data.
